version: "3"
services:
  web:
    image: garylawler/javahello:attempt1
    ports:
      - "4000:8080"
    networks:
      - webnet
  redis:
      image: redis
      ports:
        - "6379:6379"
      volumes:
        - "/home/docker/data:/data"
      command: redis-server --appendonly yes --protected-mode no
      networks:
        - webnet
networks:
  webnet:
